version: '3.7'
services:
  eureka:
    build: ./discovery-service/build/docker
    container_name: discovery
    image: discovery-image:latest
    networks:
      - eureka-network
    restart: always
    ports:
      - 8761:8761
  mongo:
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - mongo-network
    image: mongo:latest
    restart: always
  mongo-express:
    container_name: mongo-client
    image: mongo-express:latest
    restart: always
    networks:
      - mongo-network
    ports:
      - 8081:8081
  storage:
    depends_on:
      - eureka
      - mongo
    build: ./repository-service/build/docker
    container_name: storage
    image: storage-image:latest
    links:
      - mongo
      - eureka
    networks:
      - mongo-network
      - eureka-network
    restart: always
    ports:
      - 10001:10001

  es:
    container_name: elasticsearch
    image: elasticsearch:7.5.2
    networks:
      - es-network
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: >-
        -Xmx512m -Xms512m
      discovery.type: single-node
  search:
    depends_on:
      - es
      - eureka
    build: ./search-service/build/docker
    container_name: search
    image: search-image:latest
    links:
      - es
      - eureka
    networks:
      - es-network
      - eureka-network
    restart: always
    ports:
      - 10002:10002


networks:
  mongo-network:
  eureka-network:
  es-network:
volumes:
  es: {}
