spring:
  application.name: search
  jmx.enabled: false
  kafka:
    bootstrap-servers: localhost:9093
server.port: 10002

elasticHost: localhost

eureka:
  instance:
    hostname: search
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

management.endpoints.web.exposure.include: '*'
